Hinzufügen von SQL Statements
pbDS2h17a/VPR pull request #25
Opened 2019-01-17 15:54 UTC by FrederikT

In der Klasse SQL Helper wurden unten einige Methoden zum einfügen bzw. Ändern von Daten in der Datenbank hinzugefügt.

2019-01-18 05:02 UTC, BastiX2 reviewed
Schreibweise von ID -> Id und Army -> Unit um konsitent mit codebase zu bleiben

2019-01-18 05:03 UTC, BastiX2 requested changes
Schreibweise von ID -> Id und Army -> Unit um konsitent mit codebase zu bleiben

2019-01-22 10:57 UTC, FrederikT commented
Variablen Wurden Angepasst

2019-01-22 11:10 UTC, BastiX2 approved these changes

2019-01-22 11:10 UTC, merged